language: python
python: "3.5"
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install python-coveralls
  - mkdir -p var/www/static var/www/media
  - scripts/genconfig.py config/env/production.cfg
  - buildout
script:
  - py.test -vvra --tb=native --flake8 --doctest-modules seimas
after_success:
  - coveralls
# cache: pip seems not to work if `install` is replaced (https://github.com/travis-ci/travis-ci/issues/3239)
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
