language: python
python: "3.5"
install:
  - pip install -e .
  - pip install python-coveralls
  - mkdir -p var/www/static var/www/media
script:
  - py.test -vvra --tb=native --flake8 --doctest-modules seimas
after_success:
  - coveralls
